repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
      # - id: go-lint
      # - id: go-imports
      # - id: go-cyclo
      #   args: [-over=15]
      # - id: validate-toml
      - id: no-go-testing
      # - id: golangci-lint
      # - id: go-critic
      # - id: go-unit-tests
      # - id: go-build
      # - id: go-mod-tidy

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-mod-tidy-repo

  # - repo: https://github.com/compilerla/conventional-pre-commit
  #   rev: v2.1.1
  #   hooks:
  #     - id: conventional-pre-commit
  #       stages: [commit-msg]
  #       args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
